/** Scrabble Games
 * AUTORS: 	Juan David Tique Triana 	             -	20181020046
 *	Johnatan GuillermoRuiz Bautista     -	20181020034
 *	Jos� Luis Quintero Ca�izalez           - 	20181020061
 * */
package Visual;
/**
 *
 * @author estudiantes
 */
public class FRMTablero extends javax.swing.JFrame {

    /**
     * Creates new form FRMTablero
     */
    public FRMTablero() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnA1 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnA8 = new javax.swing.JButton();
        btnA9 = new javax.swing.JButton();
        btnA10 = new javax.swing.JButton();
        btnA11 = new javax.swing.JButton();
        btnA12 = new javax.swing.JButton();
        btnA13 = new javax.swing.JButton();
        btnA14 = new javax.swing.JButton();
        btnA15 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnB6 = new javax.swing.JButton();
        btnB7 = new javax.swing.JButton();
        btnB8 = new javax.swing.JButton();
        btnB9 = new javax.swing.JButton();
        btnB10 = new javax.swing.JButton();
        btnB11 = new javax.swing.JButton();
        btnB12 = new javax.swing.JButton();
        btnB13 = new javax.swing.JButton();
        btnB14 = new javax.swing.JButton();
        btnB15 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        btnC6 = new javax.swing.JButton();
        btnC7 = new javax.swing.JButton();
        btnC8 = new javax.swing.JButton();
        btnC9 = new javax.swing.JButton();
        btnC10 = new javax.swing.JButton();
        btnC11 = new javax.swing.JButton();
        btnC12 = new javax.swing.JButton();
        btnC13 = new javax.swing.JButton();
        btnC14 = new javax.swing.JButton();
        btnC15 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnD7 = new javax.swing.JButton();
        btnD8 = new javax.swing.JButton();
        btnD9 = new javax.swing.JButton();
        btnD10 = new javax.swing.JButton();
        btnD11 = new javax.swing.JButton();
        btnD12 = new javax.swing.JButton();
        btnD13 = new javax.swing.JButton();
        btnD14 = new javax.swing.JButton();
        btnD15 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        btnE6 = new javax.swing.JButton();
        btnE7 = new javax.swing.JButton();
        btnE8 = new javax.swing.JButton();
        btnE9 = new javax.swing.JButton();
        btnE10 = new javax.swing.JButton();
        btnE11 = new javax.swing.JButton();
        btnE12 = new javax.swing.JButton();
        btnE13 = new javax.swing.JButton();
        btnE14 = new javax.swing.JButton();
        btnE15 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnF6 = new javax.swing.JButton();
        btnF7 = new javax.swing.JButton();
        btnF8 = new javax.swing.JButton();
        btnF9 = new javax.swing.JButton();
        btnF10 = new javax.swing.JButton();
        btnF11 = new javax.swing.JButton();
        btnF12 = new javax.swing.JButton();
        btnF13 = new javax.swing.JButton();
        btnF14 = new javax.swing.JButton();
        btnF15 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnG6 = new javax.swing.JButton();
        btnG7 = new javax.swing.JButton();
        btnG8 = new javax.swing.JButton();
        btnG9 = new javax.swing.JButton();
        btnG10 = new javax.swing.JButton();
        btnG11 = new javax.swing.JButton();
        btnG12 = new javax.swing.JButton();
        btnG13 = new javax.swing.JButton();
        btnG14 = new javax.swing.JButton();
        btnG15 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnH6 = new javax.swing.JButton();
        btnH7 = new javax.swing.JButton();
        btnH8 = new javax.swing.JButton();
        btnH9 = new javax.swing.JButton();
        btnH10 = new javax.swing.JButton();
        btnH11 = new javax.swing.JButton();
        btnH12 = new javax.swing.JButton();
        btnH13 = new javax.swing.JButton();
        btnH14 = new javax.swing.JButton();
        btnH15 = new javax.swing.JButton();
        btnI1 = new javax.swing.JButton();
        btnI2 = new javax.swing.JButton();
        btnI3 = new javax.swing.JButton();
        btnI4 = new javax.swing.JButton();
        btnI5 = new javax.swing.JButton();
        btnI6 = new javax.swing.JButton();
        btnI7 = new javax.swing.JButton();
        btnI8 = new javax.swing.JButton();
        btnI9 = new javax.swing.JButton();
        btnI10 = new javax.swing.JButton();
        btnI11 = new javax.swing.JButton();
        btnI12 = new javax.swing.JButton();
        btnI13 = new javax.swing.JButton();
        btnI14 = new javax.swing.JButton();
        btnI15 = new javax.swing.JButton();
        btnJ1 = new javax.swing.JButton();
        btnJ2 = new javax.swing.JButton();
        btnJ3 = new javax.swing.JButton();
        btnJ4 = new javax.swing.JButton();
        btnJ5 = new javax.swing.JButton();
        btnJ6 = new javax.swing.JButton();
        btnJ7 = new javax.swing.JButton();
        btnJ8 = new javax.swing.JButton();
        btnJ9 = new javax.swing.JButton();
        btnJ10 = new javax.swing.JButton();
        btnJ11 = new javax.swing.JButton();
        btnJ12 = new javax.swing.JButton();
        btnJ13 = new javax.swing.JButton();
        btnJ14 = new javax.swing.JButton();
        btnJ15 = new javax.swing.JButton();
        btnK1 = new javax.swing.JButton();
        btnK2 = new javax.swing.JButton();
        btnK3 = new javax.swing.JButton();
        btnK4 = new javax.swing.JButton();
        btnK5 = new javax.swing.JButton();
        btnK6 = new javax.swing.JButton();
        btnK7 = new javax.swing.JButton();
        btnK8 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setMinimumSize(new java.awt.Dimension(750, 750));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 750));
        jPanel2.setLayout(new java.awt.GridLayout(15, 15));

        btnA1.setActionCommand("btnA1");
        btnA1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA1.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA1);

        btnA2.setActionCommand("btnA1");
        btnA2.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA2.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA2.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA2);

        btnA3.setActionCommand("btnA1");
        btnA3.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA3.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA3);

        btnA4.setActionCommand("btnA1");
        btnA4.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA4.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA4);

        btnA5.setActionCommand("btnA1");
        btnA5.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA5.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA5);

        btnA6.setActionCommand("btnA1");
        btnA6.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA6.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA6.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA6);

        btnA7.setActionCommand("btnA1");
        btnA7.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA7.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA7.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA7);

        btnA8.setActionCommand("btnA1");
        btnA8.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA8.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA8.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA8);

        btnA9.setActionCommand("btnA1");
        btnA9.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA9.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA9.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA9);

        btnA10.setActionCommand("btnA1");
        btnA10.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA10.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA10.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA10);

        btnA11.setActionCommand("btnA1");
        btnA11.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA11.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA11.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA11);

        btnA12.setActionCommand("btnA1");
        btnA12.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA12.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA12.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA12);

        btnA13.setActionCommand("btnA1");
        btnA13.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA13.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA13.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA13);

        btnA14.setActionCommand("btnA1");
        btnA14.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA14.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA14.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA14);

        btnA15.setActionCommand("btnA1");
        btnA15.setMaximumSize(new java.awt.Dimension(50, 50));
        btnA15.setMinimumSize(new java.awt.Dimension(50, 50));
        btnA15.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel2.add(btnA15);

        btnB1.setText("jButton1");
        jPanel2.add(btnB1);

        btnB2.setText("jButton1");
        jPanel2.add(btnB2);

        btnB3.setText("jButton1");
        jPanel2.add(btnB3);

        btnB4.setText("jButton1");
        jPanel2.add(btnB4);

        btnB5.setText("jButton1");
        jPanel2.add(btnB5);

        btnB6.setText("jButton1");
        jPanel2.add(btnB6);

        btnB7.setText("jButton1");
        jPanel2.add(btnB7);

        btnB8.setText("jButton1");
        jPanel2.add(btnB8);

        btnB9.setText("jButton1");
        jPanel2.add(btnB9);

        btnB10.setText("jButton1");
        jPanel2.add(btnB10);

        btnB11.setText("jButton1");
        jPanel2.add(btnB11);

        btnB12.setText("jButton1");
        jPanel2.add(btnB12);

        btnB13.setText("jButton1");
        jPanel2.add(btnB13);

        btnB14.setText("jButton1");
        jPanel2.add(btnB14);

        btnB15.setText("jButton1");
        jPanel2.add(btnB15);

        btnC1.setText("jButton1");
        jPanel2.add(btnC1);

        btnC2.setText("jButton1");
        jPanel2.add(btnC2);

        btnC3.setText("jButton1");
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnC3);

        btnC4.setText("jButton1");
        jPanel2.add(btnC4);

        btnC5.setText("jButton1");
        jPanel2.add(btnC5);

        btnC6.setText("jButton1");
        jPanel2.add(btnC6);

        btnC7.setText("jButton1");
        jPanel2.add(btnC7);

        btnC8.setText("jButton1");
        jPanel2.add(btnC8);

        btnC9.setText("jButton1");
        jPanel2.add(btnC9);

        btnC10.setText("jButton1");
        jPanel2.add(btnC10);

        btnC11.setText("jButton1");
        jPanel2.add(btnC11);

        btnC12.setText("jButton1");
        jPanel2.add(btnC12);

        btnC13.setText("jButton1");
        jPanel2.add(btnC13);

        btnC14.setText("jButton1");
        jPanel2.add(btnC14);

        btnC15.setText("jButton1");
        jPanel2.add(btnC15);

        btnD1.setText("jButton1");
        jPanel2.add(btnD1);

        btnD2.setText("jButton1");
        jPanel2.add(btnD2);

        btnD3.setText("jButton1");
        jPanel2.add(btnD3);

        btnD4.setText("jButton1");
        jPanel2.add(btnD4);

        btnD5.setText("jButton1");
        jPanel2.add(btnD5);

        btnD6.setText("jButton1");
        jPanel2.add(btnD6);

        btnD7.setText("jButton1");
        jPanel2.add(btnD7);

        btnD8.setText("jButton1");
        jPanel2.add(btnD8);

        btnD9.setText("jButton1");
        jPanel2.add(btnD9);

        btnD10.setText("jButton1");
        jPanel2.add(btnD10);

        btnD11.setText("jButton1");
        jPanel2.add(btnD11);

        btnD12.setText("jButton1");
        jPanel2.add(btnD12);

        btnD13.setText("jButton1");
        jPanel2.add(btnD13);

        btnD14.setText("jButton1");
        jPanel2.add(btnD14);

        btnD15.setText("jButton1");
        jPanel2.add(btnD15);

        btnE1.setText("jButton1");
        jPanel2.add(btnE1);

        btnE2.setText("jButton1");
        jPanel2.add(btnE2);

        btnE3.setText("jButton1");
        jPanel2.add(btnE3);

        btnE4.setText("jButton1");
        jPanel2.add(btnE4);

        btnE5.setText("jButton1");
        jPanel2.add(btnE5);

        btnE6.setText("jButton1");
        jPanel2.add(btnE6);

        btnE7.setText("jButton1");
        jPanel2.add(btnE7);

        btnE8.setText("jButton1");
        jPanel2.add(btnE8);

        btnE9.setText("jButton1");
        jPanel2.add(btnE9);

        btnE10.setText("jButton1");
        jPanel2.add(btnE10);

        btnE11.setText("jButton1");
        jPanel2.add(btnE11);

        btnE12.setText("jButton1");
        jPanel2.add(btnE12);

        btnE13.setText("jButton1");
        jPanel2.add(btnE13);

        btnE14.setText("jButton1");
        jPanel2.add(btnE14);

        btnE15.setText("jButton1");
        jPanel2.add(btnE15);

        btnF1.setText("jButton1");
        jPanel2.add(btnF1);

        btnF2.setText("jButton1");
        jPanel2.add(btnF2);

        btnF3.setText("jButton1");
        jPanel2.add(btnF3);

        btnF4.setText("jButton1");
        jPanel2.add(btnF4);

        btnF5.setText("jButton1");
        jPanel2.add(btnF5);

        btnF6.setText("jButton1");
        jPanel2.add(btnF6);

        btnF7.setText("jButton1");
        jPanel2.add(btnF7);

        btnF8.setText("jButton1");
        jPanel2.add(btnF8);

        btnF9.setText("jButton1");
        jPanel2.add(btnF9);

        btnF10.setText("jButton1");
        jPanel2.add(btnF10);

        btnF11.setText("jButton1");
        jPanel2.add(btnF11);

        btnF12.setText("jButton1");
        jPanel2.add(btnF12);

        btnF13.setText("jButton1");
        jPanel2.add(btnF13);

        btnF14.setText("jButton1");
        jPanel2.add(btnF14);

        btnF15.setText("jButton1");
        jPanel2.add(btnF15);

        btnG1.setText("jButton1");
        jPanel2.add(btnG1);

        btnG2.setText("jButton1");
        jPanel2.add(btnG2);

        btnG3.setText("jButton1");
        jPanel2.add(btnG3);

        btnG4.setText("jButton1");
        jPanel2.add(btnG4);

        btnG5.setText("jButton1");
        jPanel2.add(btnG5);

        btnG6.setText("jButton1");
        jPanel2.add(btnG6);

        btnG7.setText("jButton1");
        jPanel2.add(btnG7);

        btnG8.setText("jButton1");
        jPanel2.add(btnG8);

        btnG9.setText("jButton1");
        jPanel2.add(btnG9);

        btnG10.setText("jButton1");
        jPanel2.add(btnG10);

        btnG11.setText("jButton1");
        jPanel2.add(btnG11);

        btnG12.setText("jButton1");
        jPanel2.add(btnG12);

        btnG13.setText("jButton1");
        jPanel2.add(btnG13);

        btnG14.setText("jButton1");
        jPanel2.add(btnG14);

        btnG15.setText("jButton1");
        jPanel2.add(btnG15);

        btnH1.setText("jButton1");
        jPanel2.add(btnH1);

        btnH2.setText("jButton1");
        jPanel2.add(btnH2);

        btnH3.setText("jButton1");
        jPanel2.add(btnH3);

        btnH4.setText("jButton1");
        jPanel2.add(btnH4);

        btnH5.setText("jButton1");
        jPanel2.add(btnH5);

        btnH6.setText("jButton1");
        jPanel2.add(btnH6);

        btnH7.setText("jButton1");
        jPanel2.add(btnH7);

        btnH8.setText("jButton1");
        jPanel2.add(btnH8);

        btnH9.setText("jButton1");
        jPanel2.add(btnH9);

        btnH10.setText("jButton1");
        jPanel2.add(btnH10);

        btnH11.setText("jButton1");
        jPanel2.add(btnH11);

        btnH12.setText("jButton1");
        jPanel2.add(btnH12);

        btnH13.setText("jButton1");
        jPanel2.add(btnH13);

        btnH14.setText("jButton1");
        jPanel2.add(btnH14);

        btnH15.setText("jButton1");
        jPanel2.add(btnH15);

        btnI1.setText("jButton1");
        jPanel2.add(btnI1);

        btnI2.setText("jButton1");
        jPanel2.add(btnI2);

        btnI3.setText("jButton1");
        jPanel2.add(btnI3);

        btnI4.setText("jButton1");
        jPanel2.add(btnI4);

        btnI5.setText("jButton1");
        jPanel2.add(btnI5);

        btnI6.setText("jButton1");
        jPanel2.add(btnI6);

        btnI7.setText("jButton1");
        jPanel2.add(btnI7);

        btnI8.setText("jButton1");
        jPanel2.add(btnI8);

        btnI9.setText("jButton1");
        jPanel2.add(btnI9);

        btnI10.setText("jButton1");
        jPanel2.add(btnI10);

        btnI11.setText("jButton1");
        jPanel2.add(btnI11);

        btnI12.setText("jButton1");
        jPanel2.add(btnI12);

        btnI13.setText("jButton1");
        jPanel2.add(btnI13);

        btnI14.setText("jButton1");
        jPanel2.add(btnI14);

        btnI15.setText("jButton1");
        jPanel2.add(btnI15);

        btnJ1.setText("jButton1");
        jPanel2.add(btnJ1);

        btnJ2.setText("jButton1");
        jPanel2.add(btnJ2);

        btnJ3.setText("jButton1");
        jPanel2.add(btnJ3);

        btnJ4.setText("jButton1");
        jPanel2.add(btnJ4);

        btnJ5.setText("jButton1");
        jPanel2.add(btnJ5);

        btnJ6.setText("jButton1");
        jPanel2.add(btnJ6);

        btnJ7.setText("jButton1");
        jPanel2.add(btnJ7);

        btnJ8.setText("jButton1");
        jPanel2.add(btnJ8);

        btnJ9.setText("jButton1");
        jPanel2.add(btnJ9);

        btnJ10.setText("jButton1");
        jPanel2.add(btnJ10);

        btnJ11.setText("jButton1");
        jPanel2.add(btnJ11);

        btnJ12.setText("jButton1");
        jPanel2.add(btnJ12);

        btnJ13.setText("jButton1");
        jPanel2.add(btnJ13);

        btnJ14.setText("jButton1");
        jPanel2.add(btnJ14);

        btnJ15.setText("jButton1");
        jPanel2.add(btnJ15);

        btnK1.setText("jButton1");
        jPanel2.add(btnK1);

        btnK2.setText("jButton1");
        jPanel2.add(btnK2);

        btnK3.setText("jButton1");
        jPanel2.add(btnK3);

        btnK4.setText("jButton1");
        jPanel2.add(btnK4);

        btnK5.setText("jButton1");
        jPanel2.add(btnK5);

        btnK6.setText("jButton1");
        jPanel2.add(btnK6);

        btnK7.setText("jButton1");
        jPanel2.add(btnK7);

        btnK8.setText("jButton1");
        jPanel2.add(btnK8);

        jButton159.setText("jButton1");
        jPanel2.add(jButton159);

        jButton160.setText("jButton1");
        jPanel2.add(jButton160);

        jButton161.setText("jButton1");
        jPanel2.add(jButton161);

        jButton162.setText("jButton1");
        jPanel2.add(jButton162);

        jButton163.setText("jButton1");
        jPanel2.add(jButton163);

        jButton164.setText("jButton1");
        jPanel2.add(jButton164);

        jButton165.setText("jButton1");
        jPanel2.add(jButton165);

        jButton166.setText("jButton1");
        jPanel2.add(jButton166);

        jButton167.setText("jButton1");
        jPanel2.add(jButton167);

        jButton168.setText("jButton1");
        jPanel2.add(jButton168);

        jButton169.setText("jButton1");
        jPanel2.add(jButton169);

        jButton170.setText("jButton1");
        jPanel2.add(jButton170);

        jButton171.setText("jButton1");
        jPanel2.add(jButton171);

        jButton172.setText("jButton1");
        jPanel2.add(jButton172);

        jButton173.setText("jButton1");
        jPanel2.add(jButton173);

        jButton174.setText("jButton1");
        jPanel2.add(jButton174);

        jButton175.setText("jButton1");
        jPanel2.add(jButton175);

        jButton176.setText("jButton1");
        jPanel2.add(jButton176);

        jButton177.setText("jButton1");
        jPanel2.add(jButton177);

        jButton178.setText("jButton1");
        jPanel2.add(jButton178);

        jButton179.setText("jButton1");
        jPanel2.add(jButton179);

        jButton180.setText("jButton1");
        jPanel2.add(jButton180);

        jButton181.setText("jButton1");
        jPanel2.add(jButton181);

        jButton182.setText("jButton1");
        jPanel2.add(jButton182);

        jButton183.setText("jButton1");
        jPanel2.add(jButton183);

        jButton184.setText("jButton1");
        jPanel2.add(jButton184);

        jButton185.setText("jButton1");
        jPanel2.add(jButton185);

        jButton186.setText("jButton1");
        jPanel2.add(jButton186);

        jButton187.setText("jButton1");
        jPanel2.add(jButton187);

        jButton188.setText("jButton1");
        jPanel2.add(jButton188);

        jButton189.setText("jButton1");
        jPanel2.add(jButton189);

        jButton190.setText("jButton1");
        jPanel2.add(jButton190);

        jButton191.setText("jButton1");
        jPanel2.add(jButton191);

        jButton192.setText("jButton1");
        jPanel2.add(jButton192);

        jButton193.setText("jButton1");
        jPanel2.add(jButton193);

        jButton194.setText("jButton1");
        jPanel2.add(jButton194);

        jButton195.setText("jButton1");
        jPanel2.add(jButton195);

        jButton196.setText("jButton1");
        jPanel2.add(jButton196);

        jButton197.setText("jButton1");
        jPanel2.add(jButton197);

        jButton198.setText("jButton1");
        jPanel2.add(jButton198);

        jButton199.setText("jButton1");
        jPanel2.add(jButton199);

        jButton200.setText("jButton1");
        jPanel2.add(jButton200);

        jButton201.setText("jButton1");
        jPanel2.add(jButton201);

        jButton202.setText("jButton1");
        jPanel2.add(jButton202);

        jButton203.setText("jButton1");
        jPanel2.add(jButton203);

        jButton204.setText("jButton1");
        jPanel2.add(jButton204);

        jButton205.setText("jButton1");
        jPanel2.add(jButton205);

        jButton206.setText("jButton1");
        jPanel2.add(jButton206);

        jButton207.setText("jButton1");
        jPanel2.add(jButton207);

        jButton208.setText("jButton1");
        jPanel2.add(jButton208);

        jButton209.setText("jButton1");
        jPanel2.add(jButton209);

        jButton210.setText("jButton1");
        jPanel2.add(jButton210);

        jButton211.setText("jButton1");
        jPanel2.add(jButton211);

        jButton212.setText("jButton1");
        jPanel2.add(jButton212);

        jButton213.setText("jButton1");
        jPanel2.add(jButton213);

        jButton214.setText("jButton1");
        jPanel2.add(jButton214);

        jButton215.setText("jButton1");
        jPanel2.add(jButton215);

        jButton216.setText("jButton1");
        jPanel2.add(jButton216);

        jButton217.setText("jButton1");
        jPanel2.add(jButton217);

        jButton218.setText("jButton1");
        jPanel2.add(jButton218);

        jButton219.setText("jButton1");
        jPanel2.add(jButton219);

        jButton220.setText("jButton1");
        jPanel2.add(jButton220);

        jButton221.setText("jButton1");
        jPanel2.add(jButton221);

        jButton222.setText("jButton1");
        jPanel2.add(jButton222);

        jButton223.setText("jButton1");
        jPanel2.add(jButton223);

        jButton224.setText("jButton1");
        jPanel2.add(jButton224);

        jButton225.setText("jButton1");
        jPanel2.add(jButton225);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FRMTablero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA10;
    private javax.swing.JButton btnA11;
    private javax.swing.JButton btnA12;
    private javax.swing.JButton btnA13;
    private javax.swing.JButton btnA14;
    private javax.swing.JButton btnA15;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnA6;
    private javax.swing.JButton btnA7;
    private javax.swing.JButton btnA8;
    private javax.swing.JButton btnA9;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB10;
    private javax.swing.JButton btnB11;
    private javax.swing.JButton btnB12;
    private javax.swing.JButton btnB13;
    private javax.swing.JButton btnB14;
    private javax.swing.JButton btnB15;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnB5;
    private javax.swing.JButton btnB6;
    private javax.swing.JButton btnB7;
    private javax.swing.JButton btnB8;
    private javax.swing.JButton btnB9;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC10;
    private javax.swing.JButton btnC11;
    private javax.swing.JButton btnC12;
    private javax.swing.JButton btnC13;
    private javax.swing.JButton btnC14;
    private javax.swing.JButton btnC15;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnC5;
    private javax.swing.JButton btnC6;
    private javax.swing.JButton btnC7;
    private javax.swing.JButton btnC8;
    private javax.swing.JButton btnC9;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD10;
    private javax.swing.JButton btnD11;
    private javax.swing.JButton btnD12;
    private javax.swing.JButton btnD13;
    private javax.swing.JButton btnD14;
    private javax.swing.JButton btnD15;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnD5;
    private javax.swing.JButton btnD6;
    private javax.swing.JButton btnD7;
    private javax.swing.JButton btnD8;
    private javax.swing.JButton btnD9;
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnE10;
    private javax.swing.JButton btnE11;
    private javax.swing.JButton btnE12;
    private javax.swing.JButton btnE13;
    private javax.swing.JButton btnE14;
    private javax.swing.JButton btnE15;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnE3;
    private javax.swing.JButton btnE4;
    private javax.swing.JButton btnE5;
    private javax.swing.JButton btnE6;
    private javax.swing.JButton btnE7;
    private javax.swing.JButton btnE8;
    private javax.swing.JButton btnE9;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnF10;
    private javax.swing.JButton btnF11;
    private javax.swing.JButton btnF12;
    private javax.swing.JButton btnF13;
    private javax.swing.JButton btnF14;
    private javax.swing.JButton btnF15;
    private javax.swing.JButton btnF2;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnF5;
    private javax.swing.JButton btnF6;
    private javax.swing.JButton btnF7;
    private javax.swing.JButton btnF8;
    private javax.swing.JButton btnF9;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG10;
    private javax.swing.JButton btnG11;
    private javax.swing.JButton btnG12;
    private javax.swing.JButton btnG13;
    private javax.swing.JButton btnG14;
    private javax.swing.JButton btnG15;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnG4;
    private javax.swing.JButton btnG5;
    private javax.swing.JButton btnG6;
    private javax.swing.JButton btnG7;
    private javax.swing.JButton btnG8;
    private javax.swing.JButton btnG9;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH10;
    private javax.swing.JButton btnH11;
    private javax.swing.JButton btnH12;
    private javax.swing.JButton btnH13;
    private javax.swing.JButton btnH14;
    private javax.swing.JButton btnH15;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnH3;
    private javax.swing.JButton btnH4;
    private javax.swing.JButton btnH5;
    private javax.swing.JButton btnH6;
    private javax.swing.JButton btnH7;
    private javax.swing.JButton btnH8;
    private javax.swing.JButton btnH9;
    private javax.swing.JButton btnI1;
    private javax.swing.JButton btnI10;
    private javax.swing.JButton btnI11;
    private javax.swing.JButton btnI12;
    private javax.swing.JButton btnI13;
    private javax.swing.JButton btnI14;
    private javax.swing.JButton btnI15;
    private javax.swing.JButton btnI2;
    private javax.swing.JButton btnI3;
    private javax.swing.JButton btnI4;
    private javax.swing.JButton btnI5;
    private javax.swing.JButton btnI6;
    private javax.swing.JButton btnI7;
    private javax.swing.JButton btnI8;
    private javax.swing.JButton btnI9;
    private javax.swing.JButton btnJ1;
    private javax.swing.JButton btnJ10;
    private javax.swing.JButton btnJ11;
    private javax.swing.JButton btnJ12;
    private javax.swing.JButton btnJ13;
    private javax.swing.JButton btnJ14;
    private javax.swing.JButton btnJ15;
    private javax.swing.JButton btnJ2;
    private javax.swing.JButton btnJ3;
    private javax.swing.JButton btnJ4;
    private javax.swing.JButton btnJ5;
    private javax.swing.JButton btnJ6;
    private javax.swing.JButton btnJ7;
    private javax.swing.JButton btnJ8;
    private javax.swing.JButton btnJ9;
    private javax.swing.JButton btnK1;
    private javax.swing.JButton btnK2;
    private javax.swing.JButton btnK3;
    private javax.swing.JButton btnK4;
    private javax.swing.JButton btnK5;
    private javax.swing.JButton btnK6;
    private javax.swing.JButton btnK7;
    private javax.swing.JButton btnK8;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
