/** Scrabble Games
 * AUTORS: 	Juan David Tique Triana 	             -	20181020046
 *	Johnatan GuillermoRuiz Bautista     -	20181020034
 *	Jos� Luis Quintero Ca�izalez           - 	20181020061
 * */
package Visual;
/**
 *
 * @author estudiantes
 */
public class FRMTablero extends javax.swing.JFrame {

    /**
     * Creates new form FRMTablero
     */
    public FRMTablero() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(15, 15));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.GridLayout(15, 15));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1);

        jButton2.setText("jButton1");
        jPanel2.add(jButton2);

        jButton3.setText("jButton1");
        jPanel2.add(jButton3);

        jButton4.setText("jButton1");
        jPanel2.add(jButton4);

        jButton5.setText("jButton1");
        jPanel2.add(jButton5);

        jButton6.setText("jButton1");
        jPanel2.add(jButton6);

        jButton7.setText("jButton1");
        jPanel2.add(jButton7);

        jButton8.setText("jButton1");
        jPanel2.add(jButton8);

        jButton9.setText("jButton1");
        jPanel2.add(jButton9);

        jButton10.setText("jButton1");
        jPanel2.add(jButton10);

        jButton11.setText("jButton1");
        jPanel2.add(jButton11);

        jButton12.setText("jButton1");
        jPanel2.add(jButton12);

        jButton13.setText("jButton1");
        jPanel2.add(jButton13);

        jButton14.setText("jButton1");
        jPanel2.add(jButton14);

        jButton15.setText("jButton1");
        jPanel2.add(jButton15);

        jButton16.setText("jButton1");
        jPanel2.add(jButton16);

        jButton17.setText("jButton1");
        jPanel2.add(jButton17);

        jButton18.setText("jButton1");
        jPanel2.add(jButton18);

        jButton19.setText("jButton1");
        jPanel2.add(jButton19);

        jButton20.setText("jButton1");
        jPanel2.add(jButton20);

        jButton21.setText("jButton1");
        jPanel2.add(jButton21);

        jButton22.setText("jButton1");
        jPanel2.add(jButton22);

        jButton23.setText("jButton1");
        jPanel2.add(jButton23);

        jButton24.setText("jButton1");
        jPanel2.add(jButton24);

        jButton25.setText("jButton1");
        jPanel2.add(jButton25);

        jButton26.setText("jButton1");
        jPanel2.add(jButton26);

        jButton27.setText("jButton1");
        jPanel2.add(jButton27);

        jButton28.setText("jButton1");
        jPanel2.add(jButton28);

        jButton29.setText("jButton1");
        jPanel2.add(jButton29);

        jButton30.setText("jButton1");
        jPanel2.add(jButton30);

        jButton31.setText("jButton1");
        jPanel2.add(jButton31);

        jButton32.setText("jButton1");
        jPanel2.add(jButton32);

        jButton33.setText("jButton1");
        jPanel2.add(jButton33);

        jButton34.setText("jButton1");
        jPanel2.add(jButton34);

        jButton35.setText("jButton1");
        jPanel2.add(jButton35);

        jButton36.setText("jButton1");
        jPanel2.add(jButton36);

        jButton37.setText("jButton1");
        jPanel2.add(jButton37);

        jButton38.setText("jButton1");
        jPanel2.add(jButton38);

        jButton39.setText("jButton1");
        jPanel2.add(jButton39);

        jButton40.setText("jButton1");
        jPanel2.add(jButton40);

        jButton41.setText("jButton1");
        jPanel2.add(jButton41);

        jButton42.setText("jButton1");
        jPanel2.add(jButton42);

        jButton43.setText("jButton1");
        jPanel2.add(jButton43);

        jButton44.setText("jButton1");
        jPanel2.add(jButton44);

        jButton45.setText("jButton1");
        jPanel2.add(jButton45);

        jButton46.setText("jButton1");
        jPanel2.add(jButton46);

        jButton47.setText("jButton1");
        jPanel2.add(jButton47);

        jButton48.setText("jButton1");
        jPanel2.add(jButton48);

        jButton49.setText("jButton1");
        jPanel2.add(jButton49);

        jButton50.setText("jButton1");
        jPanel2.add(jButton50);

        jButton51.setText("jButton1");
        jPanel2.add(jButton51);

        jButton52.setText("jButton1");
        jPanel2.add(jButton52);

        jButton53.setText("jButton1");
        jPanel2.add(jButton53);

        jButton54.setText("jButton1");
        jPanel2.add(jButton54);

        jButton55.setText("jButton1");
        jPanel2.add(jButton55);

        jButton56.setText("jButton1");
        jPanel2.add(jButton56);

        jButton57.setText("jButton1");
        jPanel2.add(jButton57);

        jButton58.setText("jButton1");
        jPanel2.add(jButton58);

        jButton59.setText("jButton1");
        jPanel2.add(jButton59);

        jButton60.setText("jButton1");
        jPanel2.add(jButton60);

        jButton61.setText("jButton1");
        jPanel2.add(jButton61);

        jButton62.setText("jButton1");
        jPanel2.add(jButton62);

        jButton63.setText("jButton1");
        jPanel2.add(jButton63);

        jButton64.setText("jButton1");
        jPanel2.add(jButton64);

        jButton65.setText("jButton1");
        jPanel2.add(jButton65);

        jButton66.setText("jButton1");
        jPanel2.add(jButton66);

        jButton67.setText("jButton1");
        jPanel2.add(jButton67);

        jButton68.setText("jButton1");
        jPanel2.add(jButton68);

        jButton69.setText("jButton1");
        jPanel2.add(jButton69);

        jButton70.setText("jButton1");
        jPanel2.add(jButton70);

        jButton71.setText("jButton1");
        jPanel2.add(jButton71);

        jButton72.setText("jButton1");
        jPanel2.add(jButton72);

        jButton73.setText("jButton1");
        jPanel2.add(jButton73);

        jButton74.setText("jButton1");
        jPanel2.add(jButton74);

        jButton75.setText("jButton1");
        jPanel2.add(jButton75);

        jButton76.setText("jButton1");
        jPanel2.add(jButton76);

        jButton77.setText("jButton1");
        jPanel2.add(jButton77);

        jButton78.setText("jButton1");
        jPanel2.add(jButton78);

        jButton79.setText("jButton1");
        jPanel2.add(jButton79);

        jButton80.setText("jButton1");
        jPanel2.add(jButton80);

        jButton81.setText("jButton1");
        jPanel2.add(jButton81);

        jButton82.setText("jButton1");
        jPanel2.add(jButton82);

        jButton83.setText("jButton1");
        jPanel2.add(jButton83);

        jButton84.setText("jButton1");
        jPanel2.add(jButton84);

        jButton85.setText("jButton1");
        jPanel2.add(jButton85);

        jButton86.setText("jButton1");
        jPanel2.add(jButton86);

        jButton87.setText("jButton1");
        jPanel2.add(jButton87);

        jButton88.setText("jButton1");
        jPanel2.add(jButton88);

        jButton89.setText("jButton1");
        jPanel2.add(jButton89);

        jButton90.setText("jButton1");
        jPanel2.add(jButton90);

        jButton91.setText("jButton1");
        jPanel2.add(jButton91);

        jButton92.setText("jButton1");
        jPanel2.add(jButton92);

        jButton93.setText("jButton1");
        jPanel2.add(jButton93);

        jButton94.setText("jButton1");
        jPanel2.add(jButton94);

        jButton95.setText("jButton1");
        jPanel2.add(jButton95);

        jButton96.setText("jButton1");
        jPanel2.add(jButton96);

        jButton97.setText("jButton1");
        jPanel2.add(jButton97);

        jButton98.setText("jButton1");
        jPanel2.add(jButton98);

        jButton99.setText("jButton1");
        jPanel2.add(jButton99);

        jButton100.setText("jButton1");
        jPanel2.add(jButton100);

        jButton101.setText("jButton1");
        jPanel2.add(jButton101);

        jButton102.setText("jButton1");
        jPanel2.add(jButton102);

        jButton103.setText("jButton1");
        jPanel2.add(jButton103);

        jButton104.setText("jButton1");
        jPanel2.add(jButton104);

        jButton105.setText("jButton1");
        jPanel2.add(jButton105);

        jButton106.setText("jButton1");
        jPanel2.add(jButton106);

        jButton107.setText("jButton1");
        jPanel2.add(jButton107);

        jButton108.setText("jButton1");
        jPanel2.add(jButton108);

        jButton109.setText("jButton1");
        jPanel2.add(jButton109);

        jButton110.setText("jButton1");
        jPanel2.add(jButton110);

        jButton111.setText("jButton1");
        jPanel2.add(jButton111);

        jButton112.setText("jButton1");
        jPanel2.add(jButton112);

        jButton113.setText("jButton1");
        jPanel2.add(jButton113);

        jButton114.setText("jButton1");
        jPanel2.add(jButton114);

        jButton115.setText("jButton1");
        jPanel2.add(jButton115);

        jButton116.setText("jButton1");
        jPanel2.add(jButton116);

        jButton117.setText("jButton1");
        jPanel2.add(jButton117);

        jButton118.setText("jButton1");
        jPanel2.add(jButton118);

        jButton119.setText("jButton1");
        jPanel2.add(jButton119);

        jButton120.setText("jButton1");
        jPanel2.add(jButton120);

        jButton121.setText("jButton1");
        jPanel2.add(jButton121);

        jButton122.setText("jButton1");
        jPanel2.add(jButton122);

        jButton123.setText("jButton1");
        jPanel2.add(jButton123);

        jButton124.setText("jButton1");
        jPanel2.add(jButton124);

        jButton125.setText("jButton1");
        jPanel2.add(jButton125);

        jButton126.setText("jButton1");
        jPanel2.add(jButton126);

        jButton127.setText("jButton1");
        jPanel2.add(jButton127);

        jButton128.setText("jButton1");
        jPanel2.add(jButton128);

        jButton129.setText("jButton1");
        jPanel2.add(jButton129);

        jButton130.setText("jButton1");
        jPanel2.add(jButton130);

        jButton131.setText("jButton1");
        jPanel2.add(jButton131);

        jButton132.setText("jButton1");
        jPanel2.add(jButton132);

        jButton133.setText("jButton1");
        jPanel2.add(jButton133);

        jButton134.setText("jButton1");
        jPanel2.add(jButton134);

        jButton135.setText("jButton1");
        jPanel2.add(jButton135);

        jButton136.setText("jButton1");
        jPanel2.add(jButton136);

        jButton137.setText("jButton1");
        jPanel2.add(jButton137);

        jButton138.setText("jButton1");
        jPanel2.add(jButton138);

        jButton139.setText("jButton1");
        jPanel2.add(jButton139);

        jButton140.setText("jButton1");
        jPanel2.add(jButton140);

        jButton141.setText("jButton1");
        jPanel2.add(jButton141);

        jButton142.setText("jButton1");
        jPanel2.add(jButton142);

        jButton143.setText("jButton1");
        jPanel2.add(jButton143);

        jButton144.setText("jButton1");
        jPanel2.add(jButton144);

        jButton145.setText("jButton1");
        jPanel2.add(jButton145);

        jButton146.setText("jButton1");
        jPanel2.add(jButton146);

        jButton147.setText("jButton1");
        jPanel2.add(jButton147);

        jButton148.setText("jButton1");
        jPanel2.add(jButton148);

        jButton149.setText("jButton1");
        jPanel2.add(jButton149);

        jButton150.setText("jButton1");
        jPanel2.add(jButton150);

        jButton151.setText("jButton1");
        jPanel2.add(jButton151);

        jButton152.setText("jButton1");
        jPanel2.add(jButton152);

        jButton153.setText("jButton1");
        jPanel2.add(jButton153);

        jButton154.setText("jButton1");
        jPanel2.add(jButton154);

        jButton155.setText("jButton1");
        jPanel2.add(jButton155);

        jButton156.setText("jButton1");
        jPanel2.add(jButton156);

        jButton157.setText("jButton1");
        jPanel2.add(jButton157);

        jButton158.setText("jButton1");
        jPanel2.add(jButton158);

        jButton159.setText("jButton1");
        jPanel2.add(jButton159);

        jButton160.setText("jButton1");
        jPanel2.add(jButton160);

        jButton161.setText("jButton1");
        jPanel2.add(jButton161);

        jButton162.setText("jButton1");
        jPanel2.add(jButton162);

        jButton163.setText("jButton1");
        jPanel2.add(jButton163);

        jButton164.setText("jButton1");
        jPanel2.add(jButton164);

        jButton165.setText("jButton1");
        jPanel2.add(jButton165);

        jButton166.setText("jButton1");
        jPanel2.add(jButton166);

        jButton167.setText("jButton1");
        jPanel2.add(jButton167);

        jButton168.setText("jButton1");
        jPanel2.add(jButton168);

        jButton169.setText("jButton1");
        jPanel2.add(jButton169);

        jButton170.setText("jButton1");
        jPanel2.add(jButton170);

        jButton171.setText("jButton1");
        jPanel2.add(jButton171);

        jButton172.setText("jButton1");
        jPanel2.add(jButton172);

        jButton173.setText("jButton1");
        jPanel2.add(jButton173);

        jButton174.setText("jButton1");
        jPanel2.add(jButton174);

        jButton175.setText("jButton1");
        jPanel2.add(jButton175);

        jButton176.setText("jButton1");
        jPanel2.add(jButton176);

        jButton177.setText("jButton1");
        jPanel2.add(jButton177);

        jButton178.setText("jButton1");
        jPanel2.add(jButton178);

        jButton179.setText("jButton1");
        jPanel2.add(jButton179);

        jButton180.setText("jButton1");
        jPanel2.add(jButton180);

        jButton181.setText("jButton1");
        jPanel2.add(jButton181);

        jButton182.setText("jButton1");
        jPanel2.add(jButton182);

        jButton183.setText("jButton1");
        jPanel2.add(jButton183);

        jButton184.setText("jButton1");
        jPanel2.add(jButton184);

        jButton185.setText("jButton1");
        jPanel2.add(jButton185);

        jButton186.setText("jButton1");
        jPanel2.add(jButton186);

        jButton187.setText("jButton1");
        jPanel2.add(jButton187);

        jButton188.setText("jButton1");
        jPanel2.add(jButton188);

        jButton189.setText("jButton1");
        jPanel2.add(jButton189);

        jButton190.setText("jButton1");
        jPanel2.add(jButton190);

        jButton191.setText("jButton1");
        jPanel2.add(jButton191);

        jButton192.setText("jButton1");
        jPanel2.add(jButton192);

        jButton193.setText("jButton1");
        jPanel2.add(jButton193);

        jButton194.setText("jButton1");
        jPanel2.add(jButton194);

        jButton195.setText("jButton1");
        jPanel2.add(jButton195);

        jButton196.setText("jButton1");
        jPanel2.add(jButton196);

        jButton197.setText("jButton1");
        jPanel2.add(jButton197);

        jButton198.setText("jButton1");
        jPanel2.add(jButton198);

        jButton199.setText("jButton1");
        jPanel2.add(jButton199);

        jButton200.setText("jButton1");
        jPanel2.add(jButton200);

        jButton201.setText("jButton1");
        jPanel2.add(jButton201);

        jButton202.setText("jButton1");
        jPanel2.add(jButton202);

        jButton203.setText("jButton1");
        jPanel2.add(jButton203);

        jButton204.setText("jButton1");
        jPanel2.add(jButton204);

        jButton205.setText("jButton1");
        jPanel2.add(jButton205);

        jButton206.setText("jButton1");
        jPanel2.add(jButton206);

        jButton207.setText("jButton1");
        jPanel2.add(jButton207);

        jButton208.setText("jButton1");
        jPanel2.add(jButton208);

        jButton209.setText("jButton1");
        jPanel2.add(jButton209);

        jButton210.setText("jButton1");
        jPanel2.add(jButton210);

        jButton211.setText("jButton1");
        jPanel2.add(jButton211);

        jButton212.setText("jButton1");
        jPanel2.add(jButton212);

        jButton213.setText("jButton1");
        jPanel2.add(jButton213);

        jButton214.setText("jButton1");
        jPanel2.add(jButton214);

        jButton215.setText("jButton1");
        jPanel2.add(jButton215);

        jButton216.setText("jButton1");
        jPanel2.add(jButton216);

        jButton217.setText("jButton1");
        jPanel2.add(jButton217);

        jButton218.setText("jButton1");
        jPanel2.add(jButton218);

        jButton219.setText("jButton1");
        jPanel2.add(jButton219);

        jButton220.setText("jButton1");
        jPanel2.add(jButton220);

        jButton221.setText("jButton1");
        jPanel2.add(jButton221);

        jButton222.setText("jButton1");
        jPanel2.add(jButton222);

        jButton223.setText("jButton1");
        jPanel2.add(jButton223);

        jButton224.setText("jButton1");
        jPanel2.add(jButton224);

        jButton225.setText("jButton1");
        jPanel2.add(jButton225);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FRMTablero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
